#!/usr/bin/env node

var CodePush = require('./lib/code-push');
var Shell = require('./lib/shell');

var targetOS = (process.argv[2] || 'all').toLowerCase();
var deployment = process.argv[3] || 'Development';
var mandatory = false;
var appNames = {
    android: 'Trambar-Android',
    ios: 'Trambar-iOS',
};
if (process.argv[4]) {
    if (process.argv[4] === 'mandatory' || process.argv[4] === 'm') {
        mandatory = true;
    } else {
        console.log(`Unknown option: ${process.argv[4]}`);
        process.exit(-1);
    }
} else if (deployment === 'Development') {
    mandatory = true;
}

Shell.chdir(__dirname);
Shell.chdir(`cordova/trambar`);
[ 'android', 'ios' ].forEach((os) => {
    if (os === targetOS || targetOS === 'all') {
        CodePush.release(appNames[os], os, deployment, mandatory);
    }
});
Shell.chdir(__dirname);
