#!/usr/bin/env node

var File = require('./lib/file');
var Folder = require('./lib/folder');
var Git = require('./lib/git');
var Shell = require('./lib/shell');

var repo = 'git@github.com:chung-leong/trambar.git';
var wf = 'codebase';

var part = process.argv[2] || 'all';

// update or create working folder
Shell.chdir(__dirname);
var branch = Git.getCurrentBranch();
if (Folder.exists(wf)) {
    Shell.chdir(wf);
    Git.reset();
    Git.checkout(branch, { force: true });
    Git.fetch();
    Git.rebase();
    Shell.chdir(__dirname);
} else {
    Git.clone(repo, wf);
    Git.checkout(branch, { force: true });
}

if (part === 'admin' || part === 'client' || part === 'all') {
    Shell.chdir(`${wf}/common`);
    Shell.run('npm ci');
    Shell.chdir(__dirname);
}

if (part === 'admin' || part === 'all') {
    // rebuild client-side JS code
    Folder.create(`${wf}/admin/www`);
    Shell.chdir(`${wf}/admin`);
    Shell.run('npm ci');
    Shell.run('npm run build');
    Shell.chdir(__dirname);

    // copy files into Docker folder for Nginx image
    Folder.copy(`${wf}/admin/www`, 'docker/nginx/admin');
}

if (part === 'client' || part === 'all') {
    Folder.create(`${wf}/client/www`);
    Folder.create(`${wf}/client/www-cordova`);
    Shell.chdir(`${wf}/client`);
    Shell.run('npm ci');
    Shell.run('npm run build');
    Shell.run('npm run build cordova');
    Shell.chdir(__dirname);

    // copy files into Docker folder for Nginx image
    Folder.copy(`${wf}/client/www`, 'docker/nginx/client');
    // copy files into Cordova folder
    Folder.copy(`${wf}/client/www-cordova`, 'cordova/trambar/www');
} else if (part === 'cordova') {
    Folder.create(`${wf}/client/www-cordova`);
    Shell.chdir(`${wf}/client`);
    Shell.run('npm ci');
    Shell.run('npm run build cordova');
    Shell.chdir(__dirname);
    Folder.copy(`${wf}/client/www-cordova`, 'cordova/trambar/www');
}

if (part === 'backend' || part === 'all') {
    // copy files into Docker folder for Node image
    Folder.copy(`${wf}/backend`, 'docker/node/backend');
    Folder.copy(`${wf}/client/src/locales`, 'docker/node/backend/src/locales');
    Folder.copy(`${wf}/common`, 'docker/node/common');
    File.copy(`${wf}/backend/package.json`, 'docker/node/package.json');
    File.copy(`${wf}/backend/package-lock.json`, 'docker/node/package-lock.json');
    File.copy(`${wf}/backend/package.json`, 'docker/node-dev/package.json');
    File.copy(`${wf}/backend/package-lock.json`, 'docker/node-dev/package-lock.json');
}
