#!/bin/bash

if [[ -f ${CERT_PATH} && -f ${KEY_PATH} ]]; then
    mkdir -p /etc/nginx/conf.d/default.d
    cat > /etc/nginx/conf.d/default.d/ssl.conf << EOF
listen 443 ssl http2;
server_name ${DOMAIN};
ssl_certificate     ${CERT_PATH};
ssl_certificate_key ${KEY_PATH};

if (\$scheme = http) {
    return 301 https://\$host\$request_uri;
}
EOF
    chmod 600 /etc/nginx/conf.d/default.d/ssl.conf
else
    rm -f /etc/nginx/conf.d/default.d/ssl.conf
fi
